-- Between Us: private couple data model, storage, and row-level security.
create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  timezone text not null default 'UTC',
  city text not null default '',
  created_at timestamptz not null default now()
);

create table public.couples (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Us',
  invite_code text not null unique default upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 6)),
  reunion_at timestamptz,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create table public.couple_members (
  couple_id uuid not null references public.couples(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (couple_id, user_id),
  unique (user_id)
);

create table public.memories (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  created_by uuid not null references auth.users(id),
  title text not null check (char_length(title) between 1 and 120),
  note text not null default '' check (char_length(note) <= 1000),
  memory_date date not null default current_date,
  photo_path text,
  created_at timestamptz not null default now()
);

create table public.daily_questions (
  id bigint generated by default as identity primary key,
  prompt text not null unique,
  active_date date unique
);

create table public.answers (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  question_id bigint not null references public.daily_questions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  answer text not null check (char_length(answer) between 1 and 2000),
  created_at timestamptz not null default now(),
  unique (question_id, user_id)
);

create table public.date_plans (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  created_by uuid not null references auth.users(id),
  title text not null,
  details text not null default '',
  planned_for timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, display_name) values(new.id, coalesce(new.raw_user_meta_data->>'display_name', ''));
  return new;
end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_couple_member(target uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.couple_members where couple_id = target and user_id = auth.uid());
$$;

create or replace function public.create_couple(couple_name text, reunion_at timestamptz default null) returns uuid
language plpgsql security definer set search_path = public as $$
declare new_id uuid;
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;
  if exists(select 1 from public.couple_members where user_id = auth.uid()) then raise exception 'You already belong to a couple'; end if;
  insert into public.couples(name, reunion_at, created_by) values(coalesce(nullif(trim(couple_name), ''), 'Us'), reunion_at, auth.uid()) returning id into new_id;
  insert into public.couple_members(couple_id, user_id) values(new_id, auth.uid());
  return new_id;
end; $$;

create or replace function public.join_couple(code text) returns uuid
language plpgsql security definer set search_path = public as $$
declare target uuid; member_count int;
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;
  if exists(select 1 from public.couple_members where user_id = auth.uid()) then raise exception 'You already belong to a couple'; end if;
  select id into target from public.couples where invite_code = upper(trim(code));
  if target is null then raise exception 'That invite code was not found'; end if;
  select count(*) into member_count from public.couple_members where couple_id = target;
  if member_count >= 2 then raise exception 'This shared space already has two members'; end if;
  insert into public.couple_members(couple_id, user_id) values(target, auth.uid());
  return target;
end; $$;

alter table public.profiles enable row level security;
alter table public.couples enable row level security;
alter table public.couple_members enable row level security;
alter table public.memories enable row level security;
alter table public.daily_questions enable row level security;
alter table public.answers enable row level security;
alter table public.date_plans enable row level security;

create policy "profile readable by self and partner" on public.profiles for select using (
  id = auth.uid() or exists(select 1 from public.couple_members mine join public.couple_members theirs using(couple_id) where mine.user_id = auth.uid() and theirs.user_id = profiles.id)
);
create policy "update own profile" on public.profiles for update using(id = auth.uid()) with check(id = auth.uid());
create policy "members read couple" on public.couples for select using(public.is_couple_member(id));
create policy "members update couple" on public.couples for update using(public.is_couple_member(id)) with check(public.is_couple_member(id));
create policy "members read membership" on public.couple_members for select using(public.is_couple_member(couple_id));
create policy "members read memories" on public.memories for select using(public.is_couple_member(couple_id));
create policy "members add memories" on public.memories for insert with check(public.is_couple_member(couple_id) and created_by = auth.uid());
create policy "members edit memories" on public.memories for update using(public.is_couple_member(couple_id)) with check(public.is_couple_member(couple_id));
create policy "members delete memories" on public.memories for delete using(public.is_couple_member(couple_id));
create policy "signed users read questions" on public.daily_questions for select using(auth.uid() is not null);
create policy "members read answers after both answer" on public.answers for select using(
  public.is_couple_member(couple_id) and (user_id = auth.uid() or (select count(*) from public.answers a where a.couple_id = answers.couple_id and a.question_id = answers.question_id) >= 2)
);
create policy "members add own answer" on public.answers for insert with check(public.is_couple_member(couple_id) and user_id = auth.uid());
create policy "members read plans" on public.date_plans for select using(public.is_couple_member(couple_id));
create policy "members add plans" on public.date_plans for insert with check(public.is_couple_member(couple_id) and created_by = auth.uid());
create policy "members update plans" on public.date_plans for update using(public.is_couple_member(couple_id)) with check(public.is_couple_member(couple_id));
create policy "members delete plans" on public.date_plans for delete using(public.is_couple_member(couple_id));

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values('memory-photos', 'memory-photos', false, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict(id) do nothing;
create policy "members view memory photos" on storage.objects for select using (
  bucket_id = 'memory-photos' and public.is_couple_member((storage.foldername(name))[1]::uuid)
);
create policy "members upload memory photos" on storage.objects for insert with check (
  bucket_id = 'memory-photos' and public.is_couple_member((storage.foldername(name))[1]::uuid) and owner = auth.uid()
);
create policy "owners delete memory photos" on storage.objects for delete using(bucket_id = 'memory-photos' and owner = auth.uid());

insert into public.daily_questions(prompt, active_date) values
('If we had one completely free day together tomorrow, how would you want to spend it?', current_date)
on conflict do nothing;
